version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    depends_on:
      - db
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3001:3000"
  # guard:
  #   depends_on:
  #     - db
  #   build: .
  #   command: bundle exec guard --no-bundler-warning --no-interactions
  #   volumes:
  #     - .:/myapp
  #   environment:
  #     - RAILS_ENV=development
